version: '3.8'

services:
  pipeline:
    build: .
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}

  dashboard:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    working_dir: /app/dashboard
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
